import cv2
from matplotlib import pyplot as plt
image_path = '/home/kali/Desktop/image1.png'
image = cv2.imread(image_path)
if image is None:
    print("Error: Image not found. Please check the file path.")
    exit()
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
_, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)
rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(12, 8))
plt.subplot(1, 3, 1)
plt.imshow(rgb_image)
plt.title("RGB Image")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(gray_image, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.imshow(binary_image, cmap="gray")
plt.title("Binary Image")
plt.axis("off")
plt.tight_layout()
plt.show()
